name: Deploy Monitoring Stack

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      #  Authenticate to GCP 
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: voltarocks-42-sandbox
          create_credentials_file: true
          export_environment_variables: true

      #  Setup gcloud
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      #  Verify identity 
      - name: Verify identity
        run: |
          echo "Authenticated accounts:"
          gcloud auth list
          echo "Active account:"
          gcloud config get-value account
          echo "Project:"
          gcloud config get-value project

      #  Get MIG instance dynamically
      - name: Get MIG instance
        run: |
          echo "Finding Managed Instance Group..."

          MIG_NAME=$(gcloud compute instance-groups managed list \
            --zones asia-southeast1-a \
            --filter="baseInstanceName=cloud-engineer" \
            --format="value(name)")

          if [ -z "$MIG_NAME" ]; then
            echo "No MIG found!"
            exit 1
          fi

          echo "Found MIG: $MIG_NAME"

          INSTANCE=$(gcloud compute instance-groups managed list-instances $MIG_NAME \
            --zone asia-southeast1-a \
            --format="value(instance.basename())" | head -n 1)

          if [ -z "$INSTANCE" ]; then
            echo "No instance found!"
            exit 1
          fi

          echo "Using instance: $INSTANCE"
          echo "INSTANCE_NAME=$INSTANCE" >> $GITHUB_ENV

      #  Prepare monitoring directory
      - name: Prepare directory on VM
        run: |
          gcloud compute ssh ${{ env.INSTANCE_NAME }} \
            --zone asia-southeast1-a \
            --project voltarocks-42-sandbox \
            --tunnel-through-iap \
            --command="mkdir -p ~/monitoring"

      #  Copy monitoring files
      - name: Copy files to VM
        run: |
          gcloud compute scp \
            infra/monitoring/docker-compose.monitoring.yml \
            infra/monitoring/prometheus.yml \
            ${{ env.INSTANCE_NAME }}:~/monitoring \
            --zone asia-southeast1-a \
            --project voltarocks-42-sandbox \
            --tunnel-through-iap

      #  Deploy Docker Swarm stack
      - name: Deploy stack
        run: |
          gcloud compute ssh ${{ env.INSTANCE_NAME }} \
            --zone asia-southeast1-a \
            --project voltarocks-42-sandbox \
            --tunnel-through-iap \
            --command="
              set -e
              cd ~/monitoring
              sudo docker stack deploy -c docker-compose.monitoring.yml core_stack
            "